## Data Preparation

In [20]:
import vogue
import os
import cv2
import numpy as np

In [2]:
vogue.designer_show_to_download_images('miu-miu', 'spring-2024-ready-to-wear', './images')

https://assets.vogue.com/photos/651c22f1e8cf4e84fd8e3eb0/master/w_1024,c_limit/00001-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c22f2061395ced743abe9/master/w_1024,c_limit/00002-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c22f4f2154bcc982ce239/master/w_1024,c_limit/00003-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c23049bf83700cbb9f800/master/w_1024,c_limit/00004-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c2306a4e3837044494783/master/w_1024,c_limit/00005-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c231473ad00586eeb7fdd/master/w_1024,c_limit/00006-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/photos/651c2313b9c172d42f46bd78/master/w_1024,c_limit/00007-miu-miu-spring-2024-ready-to-wear-credit-gorunway.jpg
https://assets.vogue.com/ph

In [4]:
vogue.designer_show_to_download_images('helmut-lang', 'fall-2024-ready-to-wear', './images')

https://assets.vogue.com/photos/65c6933b2a206aa91f9399fc/master/w_1024,c_limit/00001-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c6933be36251e1e4662b90/master/w_1024,c_limit/00002-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c6933d9ed6e2d387b3421d/master/w_1024,c_limit/00003-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c6933ffb3881d81b1d594d/master/w_1024,c_limit/00004-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c693412483dcab332bd9d2/master/w_1024,c_limit/00005-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c693412483dcab332bd9d0/master/w_1024,c_limit/00006-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65c69343cd69dac9b188f184/master/w_1024,c_limit/00007-helmut-lang-fall-2024-ready-to-wear-credit-brand.jpg
https://assets.vogue.com/photos/65

In [5]:
labels = ['miu-miu', 'helmut-lang']
img_size = 224

In [10]:
data_dir = "./images"
image_path = os.path.join(data_dir, labels[0], 'spring-2024-ready-to-wear')
print(image_path)

./images/miu-miu/spring-2024-ready-to-wear


In [11]:
class_num = labels.index(labels[0])
print(class_num)

0


In [16]:
data = [] 
for img in os.listdir(image_path):
    try:
        img_arr = cv2.imread(os.path.join(image_path, img))[...,::-1] #convert BGR to RGB format
        resized_arr = cv2.resize(img_arr, (img_size, img_size)) # Reshaping images to preferred size
        data.append([resized_arr, class_num])
    except Exception as e:
        print(e)

'NoneType' object is not subscriptable


In [28]:
image_array = np.array(data)
print(image_array[0][0][0])

[[  3   3   3]
 [ 11  11   9]
 [ 29  30  26]
 [ 42  44  39]
 [ 50  50  48]
 [ 56  56  54]
 [ 65  65  65]
 [ 68  68  66]
 [ 74  76  75]
 [ 81  82  84]
 [ 85  88  88]
 [ 90  92  91]
 [ 98 102 103]
 [104 108 109]
 [105 111 111]
 [109 115 115]
 [113 117 118]
 [115 119 120]
 [116 120 121]
 [115 119 120]
 [115 119 119]
 [113 117 120]
 [110 113 114]
 [100 104 105]
 [ 95  98  98]
 [ 88  90  89]
 [ 85  87  86]
 [ 76  77  77]
 [ 71  71  71]
 [ 59  59  59]
 [ 53  55  52]
 [ 44  46  43]
 [ 36  38  35]
 [ 27  32  28]
 [ 20  25  21]
 [ 13  16  11]
 [  5   5   3]
 [  4   4   2]
 [ 21  23  22]
 [ 47  49  48]
 [ 58  60  58]
 [ 63  65  63]
 [ 50  52  51]
 [ 27  29  28]
 [  3   3   3]
 [  2   2   2]
 [  1   3   2]
 [ 10  10   8]
 [ 26  16  14]
 [ 54  15  17]
 [ 80  13  15]
 [ 98  22  26]
 [ 80  22  22]
 [ 34  15  14]
 [  5   6   3]
 [  7   6   5]
 [ 14  15  17]
 [ 20  21  23]
 [ 23  24  26]
 [ 20  21  22]
 [ 17  19  18]
 [ 16  18  17]
 [ 18  20  19]
 [ 20  22  21]
 [ 20  22  21]
 [ 24  26  25]
 [ 19  22 

/var/folders/99/dvbkl7kn2v5368qtns4pm2fw0000gn/T/ipykernel_75556/423790712.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  image_array = np.array(data)


In [3]:
shows = vogue.designer_to_shows('helmut-lang')
for show in shows:
    print(show)

Fall 2024 Ready-to-Wear
Pre-Fall 2024
Spring 2024 Ready-to-Wear
Fall 2022 Ready-to-Wear
Spring 2022 Ready-to-Wear
Spring 2020 Menswear
Spring 2020 Ready-to-Wear
Fall 2019 Ready-to-Wear
Spring 2018 Ready-to-Wear
Resort 2017
Spring 1998 Ready-to-Wear
Fall 2014 Ready-to-Wear
Pre-Fall 2014
Spring 2014 Ready-to-Wear
Resort 2014
Fall 2013 Ready-to-Wear
Pre-Fall 2013
Spring 2013 Ready-to-Wear
Resort 2013
Fall 2012 Ready-to-Wear
Pre-Fall 2012
Spring 2012 Ready-to-Wear
Resort 2012
Fall 2011 Ready-to-Wear
Pre-Fall 2011
Spring 2011 Ready-to-Wear
Resort 2011
Fall 2010 Ready-to-Wear
Spring 2010 Ready-to-Wear
Resort 2010
Fall 2009 Ready-to-Wear
Spring 2009 Ready-to-Wear
Resort 2009
Spring 2008 Ready-to-Wear
Spring 2008 Menswear
Resort 2008
Spring 2005 Ready-to-Wear
Spring 2005 Menswear
Fall 2004 Ready-to-Wear
Spring 2004 Ready-to-Wear
Fall 2003 Ready-to-Wear
Spring 2003 Ready-to-Wear
Fall 2002 Ready-to-Wear
Spring 2002 Ready-to-Wear
Fall 2001 Ready-to-Wear
Spring 2001 Ready-to-Wear
Fall 2000 Ready-t